name             'rsyslog'
maintainer       'Eneo Tecnología S.L.'
maintainer_email 'git@redborder.com'
license          'AGPL-3.0'
description      'Installs/Configures rsyslog in redborder manager'
version          '2.0.1'
