---
name: master branch protection

on:
  pull_request:
    branches:
      - 'master'

jobs:
  restrict_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [[ "${{ github.base_ref }}" != "development" ]]; then
            echo "Merges to master must come from development branch."
            exit 1
          fi
